apiVersion: pii.namjun.kim/v1alpha1
kind: PIIPattern
metadata:
  name: aws-credentials
  version: "1.0.0"
  maturity: stable

spec:
  displayName: "AWS Credentials"
  description: "Detects AWS Access Keys and Secret Keys"
  category: secrets

  patterns:
    # AWS Access Key ID
    - regex: 'AKIA[0-9A-Z]{16}'
      confidence: high
    # AWS Secret Access Key (in context)
    - regex: '(?i)aws.{0,20}secret.{0,20}[''"][0-9a-zA-Z/+]{40}[''"]'
      confidence: high
    # Generic AWS key pattern
    - regex: '(?i)(?:aws_?)?(?:access_?)?key_?id[''"]?\s*[:=]\s*[''"]?AKIA[0-9A-Z]{16}'
      confidence: high

  maskingStrategy:
    type: partial
    showFirst: 4
    showLast: 0
    maskChar: "*"

  severity: critical

  testCases:
    shouldMatch:
      - "AKIAIOSFODNN7EXAMPLE"
      - "aws_access_key_id = AKIAIOSFODNN7EXAMPLE"
      - 'AWS_SECRET = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"'
    shouldNotMatch:
      - "AKIA12345"
      - "NotAnAWSKey"
      - "BKIAIOSFODNN7EXAMPLE"

  references:
    - "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html"

  maintainers:
    - "@bunseokbot"

  tags:
    - secrets
    - aws
    - cloud
    - critical
