apiVersion: community.namjun.kim/v1
kind: PIIPattern
metadata:
  name: jwt-token
  version: "1.0.0"
  maturity: incubating

spec:
  displayName: "JWT Token"
  description: "Detects JSON Web Tokens (JWT) in logs"
  category: secrets

  patterns:
    # Standard JWT format: header.payload.signature
    - regex: 'eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'
      confidence: high
    # JWT in Authorization header
    - regex: '(?i)bearer\s+eyJ[A-Za-z0-9_-]*\.eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'
      confidence: high

  maskingStrategy:
    type: partial
    showFirst: 10
    showLast: 0
    maskChar: "*"

  severity: high

  testCases:
    shouldMatch:
      - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U"
      - "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U"
    shouldNotMatch:
      - "eyJhbGciOiJIUzI1"
      - "not.a.jwt"
      - "base64string"

  references:
    - "https://jwt.io/"
    - "https://datatracker.ietf.org/doc/html/rfc7519"

  maintainers:
    - "@bunseokbot"

  tags:
    - secrets
    - jwt
    - authentication
