apiVersion: pii.namjun.kim/v1alpha1
kind: PIIPattern
metadata:
  name: openai-api-key
  version: "1.0.0"
  maturity: sandbox

spec:
  displayName: "OpenAI API Key"
  description: "Detects OpenAI API keys"
  category: secrets

  patterns:
    - regex: 'sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}'
      confidence: high
    # Project API key format
    - regex: 'sk-proj-[a-zA-Z0-9_-]{80,}'
      confidence: high
    # Service account key format
    - regex: 'sk-svcacct-[a-zA-Z0-9_-]{80,}'
      confidence: high

  maskingStrategy:
    type: partial
    showFirst: 5
    showLast: 0
    maskChar: "*"

  severity: critical

  testCases:
    shouldMatch:
      - "sk-xxxxxxxxxxxxxxxxxxxxxxT3BlbkFJyyyyyyyyyyyyyyyyyyyy"
      - "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    shouldNotMatch:
      - "sk-short"
      - "not-an-openai-key"

  references:
    - "https://platform.openai.com/docs/api-reference/authentication"

  maintainers:
    - "@bunseokbot"

  tags:
    - secrets
    - openai
    - api-key
    - ai
